### ISSUE TITLE
导入Markdown功能提示成功,但是并没有加入到文档树中

### ISSUE THREAD

**Issue by aircjm** [Teakki/issue#14]
导入Markdown功能提示成功,但是并没有加入到文档树中,导出Markdown功能也有点问题,会导致有些格式错.

**Comment by debingfeng** [comment]
同问

**Comment by lealife** [comment]
windows下导入有问题, 请修改文件名后缀为.txt再尝试

**Comment by aircjm** [comment]
试了一下 txt后缀,是可以的, 不过建议支持.md  .markdown,谢谢
