### ISSUE TITLE
`` 预览样式消失问题

### ISSUE THREAD

**Issue by aircjm** [Teakki/issue#18]
在编辑中,输入  `测试` 是有样式的,会自动转换为部分代码块的样式, 但是预览会出现无样式的内容 '测试'

**Comment by aircjm** [comment]
issues是没有人处理吗?? 我看都3个月了,好像还是有这个问题,还有我之前提的图片附件的问题还是有

**Comment by lealife** [comment]
该问题暂时不会修复, 不影响使用

**Comment by lealife** [comment]
2.6已修复
