### ISSUE TITLE
点击添加文档，不能再当前选中节点下面添加文档，而是在文档树最下方添加文档

### ISSUE THREAD

**Issue by aircjm** [Teakki/issue#22]
点击添加文档，不能再当前选中节点下面添加文档，而是在文档树最下方添加文档，很影响使用，特别是文档树结构比较复杂的时候。

最好支持选中文档以及其子文档全部导出功能，目前只支持单个文档导出，费事费力。

可以参考[notion.so](https://www.notion.so)的导出和文档节点添加功能

谢谢

**Comment by lealife** [comment]
已发布

**Comment by aircjm** [comment]
发布新版本有什么新的功能吗？？
