### ISSUE TITLE
There is a xss

### ISSUE THREAD

**Issue by D4rkD0g** [Teakki/issue#24]
when add a new document, insert a picture, it can set the picture's url, so set it with ==> `"onerror="javascript:alert(document.domain);"` ,after finished that, it will be pop a window.

<img width="979" alt="vuln1" src="https://user-images.githubusercontent.com/16612623/47255080-d1d2b080-d49d-11e8-8467-11641cbd8df5.png">

**Comment by lealife** [comment]
Get it
