### ISSUE TITLE
组织、团队、空间之间的关系对于新用户来说太复杂了

### ISSUE THREAD

**Issue by scavin** [Teakki/issue#3]
完全搞不懂....

**Comment by lealife** [comment]
空间是什么?

当您注册后, TeaKKi已经为您默认建了一个空间, 那么空间是什么呢? 

空间就相当于类似Evernote, Leanote云笔记的笔记本一样, 空间下有很多笔记.

但TeaKKi的空间和云笔记的笔记本有以下不同:
- 空间下的笔记构成一棵笔记树, 笔记间存在关联
- 无子空间的概念

**Comment by lealife** [comment]
组织、团队可以先不用考虑. 新建一个组织, 组织会有团队管理

**Comment by iiuazz** [comment]
空间相当于笔记本啦!!!!

**Comment by scavin** [comment]
团队里的空间是啥？也没看到可以创建啊

**Comment by iiuazz** [comment]
组织帐户有团队. 可以将空间授权给团队. TeaKKi这套参考了Github的. Github的组织账户就可以管理团队, 可以把仓库授权给团队.

**Comment by scavin** [comment]
为什么不把 空间 叫 笔记本 或者 文档柜 之类的么？既然目前只有文档编辑功能，这个空间搞的人很晕...

**Comment by iiuazz** [comment]
@scavin 谢谢, 会考虑, 一直没找到合适的名字...

**Comment by scavin** [comment]
http://www.appinn.com/teakki/

**Comment by iiuazz** [comment]
@scavin 你是小众软件站长? 非常感谢!!
