### ISSUE TITLE
TeaKKi如何赢利？不赢利如何保证用户数据长期保存？

### ISSUE THREAD

**Issue by pixel32** [Teakki/issue#4]
费时间和精力写笔记写wiki……如果连前景都看不到，为什么要使用TeaKKi？
可替代的同类产品很多……

**Comment by iiuazz** [comment]
你好, TeaKKi的盈利模式可以借鉴Github的私有仓库, 那么可以对TeaKKi的私有空间收费. 现在暂时不会考虑.
还有企业服务, 都是盈利点.

**Comment by junhey** [comment]
真的类似产品太多了，哪个多可以用，关键是哪个用的习惯

**Comment by lealife** [comment]
类似产品不多吧, 还有什么?
